### ISSUE TITLE
启用CATALINA_PID方法，消除shutdown端口

### ISSUE THREAD

**Issue by duantihua** [beangle/sas#5]
使用shutdown端口进行停止服务，是Tomcat的默认停止方法，该方法具有平台中立的优点。
在实际使用过程中，也常常出现了停止未果的现象，不得已往往采取搜索Tomcat的Java进程，然后
发出kill的信号进行强制停机。

目前Tomcat在Linux平台上，支持在启动时指定一个参数CATALINA_PID，赋予启动后进程ID所
存储的文件位置。停止时即可使用

    bin/catalina.sh stop 3 -force

表示等待3秒后进行强行终止。该方法可以有效的结束进程。

**Comment by chanjarster** [comment]
``bin/shutdown.sh``也可以

**Comment by duantihua** [comment]
bin/shutdown.sh 内部使用catalina.sh stop。这个方法也需要配置shutdown端口，如果有进程苟活着，应该不能在可预见时间内，停止tomcat。

**Comment by duantihua** [comment]
通过定制catalina.sh实现了。
